### ISSUE TITLE
Explain why the SDK requires a service/library to access the API

### ISSUE THREAD

**Issue by mirsch** [fiskaly/fiskaly-sdk-node#10]
Can you please explain why the SDK requires a service/library to access the API?
Using a service to access a service does not make any sense to me at the moment.
What's the benefit over accessing the API directly?

**Comment by prempador** [comment]
Hi @mirsch 

Sure. 

A quick look at the documentation of the fiskaly Client says that: 

> The fiskaly Client is a stateless HTTP client which handles requests, has client-side validation for the request schema and communicates with the SMAERS component. 

So, from here we can take some points (and some points that are not mentioned in this exact sentence):

### Client Side Validation of Requests 
- Helps us improve performance by not sending all malformed requests to our backend
- Which also helps you with quicker response times
### Communicates with the SMAERS component 
- As there are multiple iterations before the SMAERS is finalized and certified there are changes in the way communication between the ERS and the SMAERS works. 
- Because of the fiskaly Client this is not visible for you, as we adapt any changes in the client directly and communication with the client doesn't change
### Stateless HTTP Client 
- Automates Authentication, refreshing the Tokens and retrying requests
### Offline Handling 
(not yet implemented, but will be available as soon as the certified system is ready)
- The fiskaly Client will handle Offline Situations and resend requests to the API as soon as the ERS has connection to the Internet again
- This provides you with a complete list of transactions in our dashboard as well as the possibility to report incidents (that caused the ERS to be offline) for later usage in the DSFinV-K
### Running two Services
You mentioned that running a second service does not make sense. This might be true, but the fiskaly-sdk-node also provides functionality to implement the fiskaly Client as a library, so this should not be an issue. You can choose any of library and service as they both have the exact same functionalities. 


Hope that helps, 
@prempador

**Comment by mirsch** [comment]
Hi @prempador 

Thanks for your explanation.
